//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Serielize.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_SERIELIZE_FORM              101
#define IDR_MAINFRAME                   128
#define IDR_SERIELTYPE                  129
#define IDC_NAME                        1000
#define IDC_TYPE                        1000
#define IDC_AGE                         1001
#define IDC_REYS                        1001
#define IDC_FIRST                       1003
#define IDC_PREV                        1004
#define IDC_NEXT                        1005
#define IDC_WORK                        1006
#define IDC_NBR                         1010
#define IDC_COST                        1011
#define IDC_NPAS                        1012
#define IDC_ST                          1013
#define IDC_DEL                         1015
#define IDC_RAZR                        1016
#define IDC_SumCOST                     1017
#define IDC_SumNPAS                     1018
#define IDC_SumST                       1019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
